; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; 串口监视器波特率，必须与代码中的 Serial.begin(115200) 保持一致
monitor_speed = 115200

; (可选) 自动上传后打开串口监视器
; monitor_filters = direct

; 添加编译标志以包含 ESP-IDF 驱动头文件
build_flags = 
    -I ~/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/driver/include
    -I ~/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_driver_touch/include

lib_deps = 
    bblanchon/ArduinoJson@^6.21.0